name: GitHub Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            # Light (pumpkin orange palette)
            dist/github-contribution-grid-snake.svg?color_snake=#ff9f43&color_dots=#161b22,#8b4513,#d2691e,#ff8c00,#ffa500
            # Dark (glowing orange)
            dist/github-contribution-grid-snake-dark.svg?color_snake=#ff7518&color_dots=#0d1117,#5a2e00,#8b4000,#d46a00,#ff9900
            # Halloween GIF version
            dist/github-contribution-grid-snake-halloween.gif?color_snake=#ff6600&color_dots=#1a1a1a,#5a3c00,#a45c00,#ff8c00,#ffb84d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "🎃 Update Halloween Snake animation [skip ci]"
